apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-docker-repo/my-app:latest  # Replace with your app's image
          ports:
            - containerPort: 8080  # Replace with the port your app listens on
          env:
            - name: ENV_VAR_NAME
              value: "value"  # Replace with your app's environment variables if any
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
